server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    gzip on;
    gzip_types text/css application/javascript text/html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache asset statici per 1 giorno
    location ~* \.(css|js|png|jpg|jpeg|gif|svg|ico)$ {
        expires 1d;
        add_header Cache-Control "public, max-age=86400";
    }
}
